### PR TITLE
Create a decorator for the methods in the tests to print information about the current scenario being tested of the given feature. / Create a decorator for the classes in a test file that prints information about the feature that is being tested. 

### PR DESCRIPTION
**Pull request by armando-montalvo**
This PR solves this two issues:
https://github.com/Enroutemx/pyroute/issues/24
https://github.com/Enroutemx/pyroute/issues/25

### CODE REVIEW

**Comment by armando-montalvo** [comment]
I know that the code is redundant, but if anyone can feedback me relating to how can I make it simpler, I'd appreciate it. (Tacos involved)

**Comment by eisaaclrubio** [comment]
@armando-montalvo please use rebase squash to meld the five commits into one.
``$ git rebase -i HEAD~5``

**Review by eisaaclrubio — COMMENTED** [review]
@armando-montalvo please use rebase squash to meld the five commits into one.
``$ git rebase -i HEAD~5``

**Comment by armando-montalvo** [comment]
Fixed.

**Pull request merged**
