### PR TITLE
Hard coded path

### LINKED ISSUE #31: Hard-coded config.json path
The module pyroute.logger contains the config.json path hard-coded. When a user tries to use a different json file, the program raises an error.

Files regarding this issue:
* pyroute/engine.py
* pyroute/logger.py
* pyroute/run.py
* pyroute/tester.py

### PR DESCRIPTION
**Pull request by eisaaclrubio**
Resolve #31

### CODE REVIEW

**Comment by atrevino-enroute** [comment]
Can you add sphinx documentation for each of the methods you modified, unit tests as well.

**Comment by atrevino89** [comment]
Can you add shpinx Documentation and unit tests for each of the methods you modified.

Also I'ld like to know if removing the hardcoded json extension will allow use to use other kind of extensions like `.cfg`, `.yml` if that's not supported yet, can we add it?

**Comment by elohimf** [comment]
@atrevino This touches multiple files, whose documentation and tests are being worked on separately by different people already. However, it would be good to check that second point @eisaaclrubio

**Comment by eisaaclrubio** [comment]
I'll take care of it!

**Comment by eisaaclrubio** [comment]
I've added some changes, by now the files that are supported are `.yaml` (and its variant `.yml`), `.json` and `.toml`.

**Pull request merged**
